FROM python:3.12

WORKDIR /app

# Copy project files
COPY . /app

RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir .

CMD ["uvicorn", "execute_api.execute_api:app", "--host", "0.0.0.0", "--port", "80"]